services:
  - type: web
    name: tele-click-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.5
      - key: WEBAPP_URL
        value: https://tele-click-bot.onrender.com
